export const en_messages = {
  // Lock Screen
  lock: {
    // Basic info
    title: 'Cf-Github-ImgBed',
    version: 'v2.0',
    desc: 'Please input your password to unlock',
    // Input related
    placeholder: 'Admin Password',
    verify: 'Verify',
    verifying: 'Verifying...',
    // Verification results
    welcome: 'Verification successful, welcome to use',
    passwordError: 'Password error, please try again',
    totpError: 'TOTP code error, please try again',
    authFailed: 'Authentication failed, please try again',
    missingKey: 'Unable to get the encrypted public key',
    // TOTP 2FA
    setupTotp: 'Setup TOTP',
    totpDesc:
      'If you have enabled two-factor authentication, please enter the verification code generated by your authenticator app',
    totpSetupTitle: 'Setup Two-Factor Authentication',
    totpSetupDesc: 'Use Google Authenticator or other authenticator apps to scan the QR code',
    totpSecret: 'Secret Key',
    totpPlaceholder: 'Enter the verification code',
    totpEnabled: 'Two-Factor Authentication Enabled',
    totpDisabled: 'Two-Factor Authentication Disabled',
  },
  // Navigation Bar
  nav: {
    logout: 'Logout',
    darkMode: 'Switch to dark mode',
    lightMode: 'Switch to light mode',
  },
  // Upload Area
  upload: {
    // Hint messages
    clickHint: 'Click to upload images (multi-select supported)',
    formatHint: 'Supports JPG, PNG, GIF, WebP, max 20MB per file, batch upload',
    dropHint: 'Click or drag to add more files',
    // Privacy related
    public: 'Public',
    private: 'Private',
    privacyQuestion: 'Is this photo public?',
    targetRepo: 'Target Repo',
    // Modal buttons
    modalTitle: 'Upload Files',
    confirm: 'Confirm Upload',
    cancel: 'Cancel',
    startUpload: 'Start Upload',
    // Upload status
    uploading: 'Uploading...',
    complete: 'Done',
    pending: 'Pending',
    completed: 'Completed',
    failed: 'Failed',
    cancelled: 'Cancelled',
    retry: 'Retry',
    retryCount: 'Retry {count}',
    remove: 'Remove from queue',
    cancelAll: 'Cancel All',
    allDone: 'All uploads complete',
    // Upload results
    successSingle: 'Upload successful!',
    successPublic: 'Upload successful! (Public)',
    successPrivate: 'Upload successful! (Private)',
    failType: 'Unsupported file type: {type}',
    failSize: 'File exceeds 20MB limit',
    failUpload: 'Upload failed: {name} - {error}',
    successCount: 'All uploads successful, {count} images',
    summary: 'Upload complete: {success} succeeded, {fail} failed, {cancel} cancelled',
    // Upload window
    minimized: 'Upload window minimized',
    minimizedTitle: 'Uploading {done}/{total}',
    notImage: 'Not an image file',
    overSize: 'Exceeds 20MB limit',
    selectFiles: 'Please select image files to upload',
    noPending: 'No files pending upload',
  },
  // Random Image
  random: {
    title: 'Random Public Image',
    refresh: 'Refresh',
    placeholder: 'Click the button above to get a random public image',
    disabled: 'Random image API is disabled',
    noImages: 'No public images found',
    fetchFailed: 'Failed to fetch random image',
  },
  // Image Gallery
  gallery: {
    // Basic info
    title: 'Image Gallery',
    count: 'Total {count} images',
    noImages: 'No images yet, upload one',
    allRepos: 'All Repos',
    // Image actions
    public: 'Public',
    private: 'Private',
    copyLink: 'Copy Link',
    delete: 'Delete',
    preview: 'Preview',
    openNew: 'Open in New Tab',
    // Search & sort
    search: 'Search images...',
    sortName: 'By Name',
    sortDate: 'By Date',
    sortSize: 'By Size',
    // Pagination
    pageInfo: '{current} / {total}',
    loading: 'Loading...',
    pagePrev: 'Previous',
    pageNext: 'Next',
    refreshing: 'Refreshing...',
    // Error messages
    loadFailed: 'Failed to load images',
  },
  // Delete Confirmation
  delete: {
    // Single delete
    title: 'Delete Image',
    message: 'Are you sure you want to delete "{name}"?\nThis action cannot be undone',
    confirm: 'Confirm Delete',
    cancel: 'Cancel',
    deleting: 'Deleting...',
    success: 'Deleted successfully',
    failed: 'Delete failed',
    // Batch delete
    batchTitle: 'Batch Delete',
    batchMessage: 'Are you sure you want to delete {count} selected images?\nThis action cannot be undone',
  },
  // Settings
  settings: {
    // Basic settings
    language: '语言 / Language',
    title: 'Settings',
    siteTitle: 'Site Title',
    siteTitlePlaceholder: 'Navigation bar title',
    siteSubtitle: 'Site Subtitle',
    siteSubtitlePlaceholder: 'Site subtitle',
    themeColor: 'Theme Color',
    // Feature settings
    maxRetries: 'Max Retries',
    maxRetriesHint: 'Current: {count}',
    pageSize: 'Images Per Page',
    pageSizeHint: 'Current: {count} images',
    // Random image API settings
    allowRandom: 'Random Image API',
    allowRandomOn: 'Enabled',
    allowRandomOff: 'Disabled',
    allowRandomDesc: 'When enabled, /api/random returns a random public image',
    randomHosts: 'Allowed Hosts',
    randomHostsHint: 'Separate multiple hosts with commas',
    randomHostsPlaceholder: 'e.g., example.com,*.test.com',
    randomHostsDesc1: 'Default * allows all hosts',
    randomHostsDesc2: 'Set specific hosts to restrict access',
    randomHostsDesc3: 'Wildcard supported: *.example.com matches all subdomains',
    // Repository management
    addRepoName: 'New Repository',
    defaultRepoName: 'Default Repository',
    repoManage: 'Manage Repositories',
    repoEmpty: 'No repositories configured',
    repoEmptyHint: 'Click to add a repository',
    repoAddFirstText: 'Add a repository first',
    repoCurrent: 'Current Repository',
    repoCustomName: 'Custom Name',
    repoName: 'Repo Name',
    repoBranch: 'Branch Name',
    repoPath: 'Path',
    repoToken: 'Token (Optional)',
    repoTokenPlaceholder: 'Leave empty to use global Token',
    repoIsPublic: 'Whether to make public',
    useThisRepo: 'Use this repo',
    repoCurrentUsing: 'Currently in use',
    repoStatusCheck: 'Check Status',
    repoStatusChecking: 'Checking if the warehouse is available...',
    checkRepoAvailableToast: 'Repository is available',
    checkRepoUnavailableToast: 'Repository is not available',
    checkRepoErrorNotFound: 'Repository not found',
    checkRepoErrorInvalidToken: 'Invalid token',
    checkRepoErrorNetwork: 'Network error',
    checkRepoErrorUnknown: 'Unknown error',
    repoDelete: 'Delete',
    repoAddText: 'Add Repository',
    repoCdnBase: 'CDN acceleration address',
    repoCdnHint: 'The public repository will utilize this CDN address to accelerate access',
    cdnBasePlaceholder: 'https://cdn.jsdmirror.com/gh',
    setActiveToast: 'Repository switched',
    removeRepoCheckToast: 'At least one repository should be retained',
    removeRepoToast: 'Repository removed',
    // Repository info
    repoInfo: 'Repository Info',
    owner: 'Owner',
    repo: 'Repo',
    branch: 'Branch',
    path: 'Path',
    notSet: 'Not set',
    configHint: 'Please configure complete repository info',
    copySecretToast: 'The token has been copied',
    // Save related
    save: 'Save Settings',
    saving: 'Saving...',
    saveSuccess: 'Settings saved',
    synced: 'Settings synced to cloud',
    syncFailed: 'Saved locally, cloud sync failed: {error}',
    localOnly: 'Saved locally (failed to sync to the cloud)',
    saveError: 'Save failed: {error}',
    syncingFromRemote: 'Syncing from cloud...',
    syncFromRemote: 'Synced from cloud',
    syncFromRemoteFailed: 'Sync from cloud failed: {error}',
    syncingToRemote: 'Syncing to cloud...',
    syncToRemoteFailed: 'Sync to cloud failed: {error}',
    detectedRemoteNewer:
      'The cloud configuration has been detected as newer and has overwritten the local configuration',
    detectedLocalNewer:
      'The local configuration has been detected as being relatively recent. Please go to settings to sync',
    // Other
    reset: 'Reset Defaults',
    resetDone: 'Settings reset to defaults',
    settingInfo: 'Configuration Info',
    loadFromRemote: 'Load from Cloud',
    uploadToRemote: 'Upload to Cloud',
  },
  // Common
  common: {
    // Copy related
    copy: 'Copy Link',
    copied: 'Link copied to clipboard',
    copyFailed: 'Copy failed, please copy manually',
    copyLink: 'Copy Link',
    // Window actions
    openNew: 'Open in New Tab',
    close: 'Close',
    // Status messages
    loading: 'Loading...',
    processing: 'Processing...',
    inTheProgress: '{action} is in progress...',
    // Button text
    confirm: 'Confirm',
    cancel: 'Cancel',
    // Error messages
    error: 'Operation failed',
    networkError: 'Network error',
    notFound: 'API not found',
    serverError: 'Internal server error',
    unauthorized: 'Unauthorized, please login again',
    loginFirst: 'Please login first',
    // Other
    operationCanceled: 'Operation canceled',
    logout: 'Logged out',
  },
  // Batch Operations
  batch: {
    // Selection related
    selected: '{count} selected',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    shortcutsHint: 'Tips: Hold down Ctrl and click on the image to enter batch mode',
    // Batch actions
    setPublic: 'Set Public',
    setPrivate: 'Set Private',
    copyLinks: 'Copy Links',
    delete: 'Batch Delete',
    deleteSuccess: '{count} images deleted',
    // Visibility batch operations
    visibilityTitle: 'Batch {action}',
    visibilityMessage: 'Are you sure you want to {action} the selected {count} images?',
    visibilitySuccess: '{action} {count} images have been processed',
    visibilityPartial: '{action} completed: {success} successfully, {fail} failed',
    visibilityFailed: '{action} failed',
  },
  // Export
  export: {
    title: 'Export Image Links',
    // Export formats
    url: 'Plain text links (one per line)',
    markdown: 'Markdown format',
    html: 'HTML img tags',
    json: 'JSON array',
    csv: 'CSV format',
    // Action buttons
    copyResult: 'Copy Result',
    download: 'Download File',
  },
  // Image Editor
  editor: {
    title: 'Image Editor',
    // Format & quality
    format: 'Format',
    original: 'Original',
    quality: 'Quality',
    // Dimensions related
    maxWidth: 'Max Width',
    originalSize: 'Original Size',
    originalWidth: 'Original Width',
    changedDimensions: 'Changed dimensions',
    // Processing results
    process: 'Process',
    noChange: 'No changes',
    estimatedSize: 'Estimated Size',
    savedSize: 'Saved Size',
  },
  // API
  api: {
    // Rate limiting & permissions
    rateLimit: 'Too many requests, please try again later',
    lackRequiredEnv: 'Missing required environment variables',
    noKV: 'KV namespace not set',
    notFound: 'API not found',
    notAuthorized: 'Unauthorized, please login again',
    lackAuthToken: 'Missing authentication token',
    wrongPassword: 'Incorrect password',
    authFailed: 'Authentication failed, please try again',
    // Random image related
    randomIsDisable: 'Random image API is disabled',
    disallowedHost: 'This hostname is not allowed to access the random image API',
    noPublicImages: 'No public images found',
    noMatchingImages: 'No matching public images found',
    fetchImageFailed: 'Failed to fetch image',
    // Upload related
    invalidFormData: 'Invalid form data',
    noUploadedImage: 'No image file provided',
    invalidFileType: 'Unsupported file type, only allow: JPG, PNG, GIF, WebP',
    fileTooLarge: 'File size exceeds limit (max 20MB)',
    // Repository related
    incompleteRepoConfig: 'Incomplete repository configuration',
    repoNotFound: 'Repository not found',
    notConfiguredRepo: 'No repository configured',
    notProvidedRepoId: 'Repository ID not provided',
    // File related
    invalidData: 'Invalid request data',
    invalidFilename: 'Invalid filename',
    fileNotExist: 'File does not exist',
    fileNotFound: 'File not found',
    getFileInfoFailed: 'Failed to get file information',
    emptyFilesList: 'Please provide a list of filenames',
    // Batch operations
    isPublicMustBeBoolean: 'isPublic must be a boolean value',
    batchFailed: 'Batch operation failed',
    // Other
    unknownError: 'Unknown error',
    saveSettingsFailed: 'Failed to save settings',
  },
};
